"""
Module: run_xai_comparison.py

Standalone execution script for comparative XAI evaluation.
Acts as the global evaluation hub, comparing localized 3D maps generated by 
SVM/CNN Explainers against the Ground Truth Voxel-Based Morphometry (VBM) results.
"""
import sys
from pathlib import Path
from typing import Optional
import pandas as pd

from Python.utils.py_logger import CustomLogger
from Python.utils.model_renderer import ModelRenderer
from Python.utils.roi_analyzer import ROIAnalyzer
from Python.utils.reset_directory import reset_directory

def run_xai_comparison(
    enable_file_logging: bool = False, 
    output_dir: Optional[Path] = None,
    input_dir: Optional[Path] = None
) -> None:
    """
    Executes the absolute comparative evaluation pipeline.
    
    PURPOSE:
        Extracts signals from NIfTI maps using a dual-logic approach:
        1. Net Impact (Directional): For Diverging Bar charts.
        2. Bloch Methodology (Absolute Mean): For Global Feature Importance Heatmaps & nDCG.
        
    Args:
        enable_file_logging (bool): If True, logs are written to disk.
        output_dir (Optional[Path]): Directory where results will be written.
        input_dir (Optional[Path]): Directory containing atlas and CSV inputs.
    """
    current_dir = Path(__file__).parent.resolve()
    base_out = output_dir.resolve() if output_dir else current_dir

    atlas_path = input_dir / "labels_Neuromorphometrics.nii"
    atlas_csv_path = input_dir / "spm_atlas_labels.csv"

    matlab_results_dir = base_out.parent / "MATLAB_Results"
    vbm_path = matlab_results_dir / "VBM_Pipeline_Results" / "Results" / "TPM_Mask_FWE_corrected_map.nii"
    
    xai_maps_dir = base_out / "SVM_XAI_Results" / "Results"
    
    comp_base = base_out / "XAI_Comparison_Results"
    results_dir = comp_base / "Results"
    plots_dir = comp_base / "Plots"
    log_dir = comp_base / "Log_Files"
    
    log = CustomLogger(name="XAI_Comparison")
    log.add_console_handler(level="DEBUG", use_colors=True)
    
    if enable_file_logging:
        reset_directory(log_dir, log)
        log_path = log_dir / "XAI_Comparison.log"
        try:
            log.add_file_handler(str(log_path), level="DEBUG")
        except OSError as e:
            log.critical(f"I/O ERROR: Cannot write to {log_path.name}")
            sys.exit(1)
    else:
        comp_base.mkdir(parents=True, exist_ok=True)

    log.info("--- Booting XAI Comparison Pipeline (Dual Logic: Net Impact & Bloch) ---")

    reset_directory(results_dir, log)
    reset_directory(plots_dir, log)
    
    analyzer = ROIAnalyzer(log)
    plotter = ModelRenderer(log, str(plots_dir))
    
    if not atlas_path.exists() or not atlas_csv_path.exists():
        log.critical(f"FATAL: Neuromorphometrics Atlas files missing in {input_dir}.")
        sys.exit(1)

    heatmap_columns = {}
    aggregated_for_matrix = {}

    log.info("Phase 1: Validating VBM Ground Truth...")
    if not vbm_path.exists():
        log.warning(f"VBM Ground Truth file not found at: {vbm_path}")
        log.warning("Proceeding with model-to-model comparison only.")
    else:
        log.info("Extracting ROI importance from VBM (Ground Truth) using Bloch Logic...")
        try:
            # BLOCH LOGIC: use_absolute=True (Mean of Absolute values)
            df_vbm = analyzer.extract_regional_importance(str(vbm_path), str(atlas_path), str(atlas_csv_path), use_absolute=True)
            
            # Since use_absolute=True, 'Mean_ROI_Signal' is already the Bloch magnitude
            vbm_scores = df_vbm.set_index('ROI_Name')['Mean_ROI_Signal']
            vbm_min, vbm_max = vbm_scores.min(), vbm_scores.max()
            vbm_norm = (vbm_scores - vbm_min) / (vbm_max - vbm_min) if vbm_max > vbm_min else vbm_scores * 0.0
            
            heatmap_columns["VBM (Ground Truth)"] = vbm_norm
            aggregated_for_matrix["VBM (Ground Truth)"] = vbm_norm
            log.success("VBM (Ground Truth) processed successfully")
        except Exception as e:
            log.error(f"Failed to process VBM Ground Truth: {e}")
    
    log.info("Phase 2: Aggregating Python XAI maps...")
    methods_dict = {
        "SVM Raw Weights (Top 1%)": list(xai_maps_dir.glob("SVM_Raw_Weights_Fold_*_Top1.nii")), 
        "SVM Raw Weights (Top 5%)": list(xai_maps_dir.glob("SVM_Raw_Weights_Fold_*_Top5.nii")), 
        "SVM Haufe (Top 1%)": list(xai_maps_dir.glob("SVM_Haufe_Fold_*_Top1.nii")),
        "SVM Haufe (Top 5%)": list(xai_maps_dir.glob("SVM_Haufe_Fold_*_Top5.nii")),
        "SVM Gaonkar (FDR 0.1)": list(xai_maps_dir.glob("SVM_Gaonkar_Fold_*_fdr01.nii")),
        "SVM Gaonkar (Bonf 0.05)": list(xai_maps_dir.glob("SVM_Gaonkar_Fold_*_bonf005.nii")),
    }
    
    for method_name, paths_list in methods_dict.items():
        if not paths_list:
            log.warning(f"No maps found for {method_name}.")
            continue
            
        log.info(f"Processing: {method_name}")
        safe_name = method_name.replace(" ", "_").replace("(", "").replace(")", "").replace("%", "")
        
        # --- 1. DIVERGING PLOTS (NET IMPACT LOGIC) ---
        # use_absolute=False: Preserves signs to show direction (AD vs CTRL)
        df_directional = analyzer.aggregate_and_normalize_maps(paths_list, str(atlas_path), str(atlas_csv_path), metric='Mean_ROI_Signal', use_absolute=False)
        if not df_directional.empty:
            div_out_path = f"Directional/Diverging_Mean_{safe_name}.png"
            plotter.plot_diverging_bars(df_directional, score_col='Mean_ROI_Signal', title=method_name, filename=div_out_path, top_k=20)

        # --- 2. HEATMAP & NDCG MATRIX (BLOCH LOGIC) ---
        # use_absolute=True: Averages the absolute values of the voxels to prevent signal cancellation
        df_bloch_agg = analyzer.aggregate_and_normalize_maps(paths_list, str(atlas_path), str(atlas_csv_path), metric='Mean_ROI_Signal', use_absolute=True)
        if not df_bloch_agg.empty:
            # The aggregator automatically creates 'Normalized_Importance' when use_absolute=True
            aggregated_for_matrix[method_name] = df_bloch_agg.set_index('ROI_Name')['Normalized_Importance']

        # --- 3. INDIVIDUAL FOLD ANALYSIS ---
        for fold_path in paths_list:
            fold_name = fold_path.stem 
            
            # Use Bloch logic (use_absolute=True) for Top20 plots and CSV exports
            df_fold_bloch = analyzer.extract_regional_importance(str(fold_path), str(atlas_path), str(atlas_csv_path), use_absolute=True)
            if df_fold_bloch.empty: continue
            
            safe_fold_name = fold_name.replace(" ", "_").replace("(", "").replace(")", "").replace("%", "")
            
            # Save Fold CSVs dynamically 
            csv_out_path = results_dir / f"{safe_fold_name}_Bloch_FeatureImportance.csv"
            csv_out_path.parent.mkdir(parents=True, exist_ok=True)
            df_fold_bloch.to_csv(str(csv_out_path), index=False)
            
            plot_out_path = f"Folds/Top20_Bloch_{safe_fold_name}.png"
            # Since use_absolute=True, 'Mean_ROI_Signal' is the absolute magnitude
            plotter.plot_top_rois(df_fold_bloch, score_col='Mean_ROI_Signal', title=f"{fold_name} (Bloch)", filename=plot_out_path, top_k=20)
            
            # Normalize fold for the Global Heatmap
            fold_scores = df_fold_bloch.set_index('ROI_Name')['Mean_ROI_Signal']
            f_min, f_max = fold_scores.min(), fold_scores.max()
            fold_norm = (fold_scores - f_min) / (f_max - f_min) if f_max > f_min else fold_scores * 0.0
            
            fold_num = fold_name.split("_Fold_")[1].split("_")[0] if "_Fold_" in fold_name else fold_name[-1]
            heatmap_columns[f"{method_name} (F{fold_num})"] = fold_norm
    
    if len(aggregated_for_matrix) > 1:
        log.info("Phase 3: Building nDCG Correlation Matrix across all methods (Bloch Logic)...")
        matrix_df = pd.DataFrame(aggregated_for_matrix).fillna(0.0)
        method_keys = list(matrix_df.columns)
        ndcg_matrix = pd.DataFrame(index=method_keys, columns=method_keys, dtype=float)
        
        full_k = len(matrix_df)
        for ref_m in method_keys:
            for comp_m in method_keys:
                true_scores = matrix_df[ref_m].values
                pred_scores = matrix_df[comp_m].values
                score = analyzer.calculate_ndcg(pred_scores, true_scores, k=full_k)
                ndcg_matrix.loc[ref_m, comp_m] = score
                
        out_matrix_path = "nDCG_Correlation_Matrix_Bloch.png"
        plotter.plot_ndcg_matrix(ndcg_matrix, out_matrix_path, title_suffix=f"Bloch Logic (K={full_k})")
    else:
        log.warning("Phase 3 Skipped: Not enough valid maps to compute nDCG Correlation Matrix.")

    if len(heatmap_columns) > 1:
        log.info("Phase 4: Building global Heatmap (all folds)...")
        heatmap_matrix = pd.DataFrame(heatmap_columns).fillna(0.0)
        
        if "VBM (Ground Truth)" in heatmap_matrix.columns:
            heatmap_matrix = heatmap_matrix.sort_values(by="VBM (Ground Truth)", ascending=False)
        else:
            heatmap_matrix = heatmap_matrix.sort_index()
            
        top_k_heat = 35
        if len(heatmap_matrix) > top_k_heat:
            heatmap_matrix = heatmap_matrix.head(top_k_heat)
            
        out_heat_path = "Heatmap_Bloch_AllFolds.png"
        plotter.plot_heatmap(heatmap_matrix, out_heat_path, title_suffix="Bloch Logic")
    else:
        log.warning("Phase 4 Skipped: Not enough valid maps to generate Heatmap.")

    log.success("--- XAI Comparison Completed ---")

if __name__ == "__main__":
    run_xai_comparison()