"""
Module: cv_manager.py

Cross-Validation Manager Module.

PURPOSE:
    Centralizes the generation of Outer and Inner folds to guarantee absolute 
    synchronization between independent predictive engines (e.g., SVM and EfficientNet).
"""
import json
import numpy as np
from sklearn.model_selection import StratifiedKFold
from typing import List, Dict, Any

class CVManager:
    """
    Generates deterministic splits for Nested Cross-Validation.
    
    PURPOSE:
        Provides both absolute indices (for Outer folds) and relative indices 
        (for Inner GridSearchCV and Deep Learning Early Stopping).
    """
    def __init__(self, outer_folds: int = 5, inner_folds: int = 5, random_state: int = 42):
        """
        Initializes the Cross-Validation Manager.
        
        Args:
            outer_folds (int): Number of outer folds
            inner_folds (int): Number of inner folds
            random_state (int): Seed for deterministic, reproducible shuffling.
        """
        self.outer_folds = outer_folds
        self.inner_folds = inner_folds
        self.random_state = random_state

    def generate_splits(self, y: np.ndarray) -> List[Dict[str, Any]]:
        """
        Computes the Stratified K-Fold indices based on the target array 'y'.
        
        PURPOSE:
            Ensures class balance across all training and testing sets. Computes 
            relative indices for inner folds
            
        Args:
            y (np.ndarray): 1D array containing the target labels (e.g., 0 for CTRL, 1 for AD).
            
        Returns:
            List[Dict[str, Any]]: A list of dictionaries containing:
                - 'fold' (int): Fold execution number.
                - 'outer_train_idx' (list): Absolute training indices.
                - 'outer_test_idx' (list): Absolute testing indices.
                - 'inner_splits_relative' (list): Tuples of relative (in_tr, in_val) indices.
        """
        outer_cv = StratifiedKFold(n_splits=self.outer_folds, shuffle=True, random_state=self.random_state)
        splits_registry = []

        for fold_idx, (train_idx, test_idx) in enumerate(outer_cv.split(np.zeros(len(y)), y), start=1):
            y_train = y[train_idx]
            
            # inner cv enerated relatively to y_train for Scikit-Learn GridSearchCV compatibility
            inner_cv = StratifiedKFold(n_splits=self.inner_folds, shuffle=True, random_state=self.random_state)
            inner_splits_relative = list(inner_cv.split(np.zeros(len(y_train)), y_train))

            splits_registry.append({
                'fold': fold_idx,
                'outer_train_idx': train_idx,
                'outer_test_idx': test_idx,
                'inner_splits_relative': inner_splits_relative
            })
            
        return splits_registry

    @staticmethod
    def save_to_json(splits_registry: List[Dict[str, Any]], subjects: np.ndarray, filepath: str) -> None:
        """
        Serializes Numpy indices to standard JSON lists and injects Subject ID signatures.
        
        PURPOSE:
            Freezes the CV topology to disk. Injects 'security_test_subjects' to 
            act as a signature. This prevents Data Leakage in decoupled 
            scripts by ensuring the loaded data strictly matches the expected topology.
            
        Args:
            splits_registry (List[Dict]): The topology generated by `generate_splits`.
            subjects (np.ndarray): Array of subject string IDs aligned with the dataset.
            filepath (str): Export path for the .json artifact.
        """
        serializable_splits = []
        for split in splits_registry:
            s_dict = {}
            for k, v in split.items():
                if isinstance(v, np.ndarray):
                    s_dict[k] = v.tolist()
                elif isinstance(v, list) and len(v) > 0 and isinstance(v[0], tuple):
                    # Handle inner_splits_relative tuples of numpy arrays
                    s_dict[k] = [[tr.tolist(), val.tolist()] for tr, val in v]
                else:
                    s_dict[k] = v
                    
            # The exact subject IDs expected in the test fold
            s_dict['security_test_subjects'] = subjects[split['outer_test_idx']].tolist()
            serializable_splits.append(s_dict)

        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(serializable_splits, f, indent=4)

    @staticmethod
    def load_from_json(filepath: str) -> List[Dict[str, Any]]:
        """
        Loads serialized splits from disk.
        """
        with open(filepath, 'r', encoding='utf-8') as f:
            return json.load(f)